export const CLUSTER3_CHANNEL_DEFAULTS = {
  firstCard: {
    id: 1,
    title: "Career Exp Channel",
    badge: "D",
    price: "4.89",
    tag: "09h 99m 99s",
    channelName: "@Discovery_Korea",
    platform: "유튜브",
    management: "개인 소유 관리",
    startYear: "2019",
    startMonth: "04",
    startDay: "26",
    rating: "7",
    status: "운영 중",
    link: "https://www.youtube.com/@Discovery_Korea",
    images: [null, null, null, null, null] as (string | null)[],
    insight: "",
    experience: "",
    metrics: "",
  },
  emptyCard: {
    title: "Career Exp Channel",
    badge: "D",
    price: "4.89",
    tag: "09h 99m 99s",
    channelName: "",
    platform: "",
    management: "",
    startYear: "",
    startMonth: "",
    startDay: "",
    rating: "",
    status: "",
    link: "",
    images: [null, null, null, null, null] as (string | null)[],
    insight: "",
    experience: "",
    metrics: "",
  },
};

export const createInitialChannelCards = () => [
  { ...CLUSTER3_CHANNEL_DEFAULTS.firstCard },
  ...Array.from({ length: 15 }, (_, i) => ({
    id: i + 2,
    ...CLUSTER3_CHANNEL_DEFAULTS.emptyCard,
  })),
];
